POST http://localhost:3024/usuarios/upload-imagem
Content-Type: multipart/form-data

--boundary123
Content-Disposition: form-data; name="image"; filename="150x150.png"
Content-Type: image/png

[dados binários da imagem]
--boundary123--